import { Inter } from "next/font/google";
import "./globals.css";
import ColorProvider from "@/modules/providers/ColorProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MenuClick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ColorProvider>
        <Toaster />
        <body className={inter.className}>{children}</body>
      </ColorProvider>
    </html>
  );
}
